media:
  path: public/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: '{fields.title}'
    fields:
      - name: title
        label: Post Title
        type: string
      - name: meta_title
        label: Meta Title (SEO)
        type: string
      - name: description
        label: Meta Description
        type: text
      - name: date
        label: Publish Date
        type: date
      - name: image
        label: Featured Image
        type: image
      - name: author
        label: Author Name
        type: string
      - name: categories
        label: Categories
        type: list
        field:
          type: string
      - name: tags
        label: Tags
        type: list
        field:
          type: string
      - name: draft
        label: Draft Mode
        type: boolean
      - name: body
        label: Article Content
        type: rich-text